---

apiVersion: v1
kind: Namespace
metadata:
  name: mongo

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
  namespace: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: mongo-db
  type: LoadBalancer

---

apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
  namespace: mongo
  labels:
    name: mongo-db
spec:
  containers:
    - image: mongo
      name: mongo
      volumeMounts:
        - name: data
          mountPath: /data/db
          subPath: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mongo-data

---

# Request a persistent volume from the cluster using a Persistent Volume Claim.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-data
  namespace: mongo
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi